[project]
name = "projekt-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest-cov>=6.1.1",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "pymupdf4llm>=0.0.21",
]
